import Head from 'next/Head'
import Link from 'next/Link'

import styles from '../styles/Navbar.module.css'

export default function Navbar() {
    return (
        <>
            <Head>
                <title>BPTran - App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <ul className={styles.navbar}>
                    <li>
                        <Link href="/">Home</Link>
                    </li>
                    <li>
                        <Link href="/escalas">Escalas</Link>
                    </li>
                    <li>
                        <Link href="/iseo">ISEO</Link>
                    </li>
                    <li>
                        <Link href="/about">Sobre</Link>
                    </li>
                </ul>
            </header>
        </>
    )
}